version: 0.2

phases:
  build:
    commands:
      - echo "Syncing files..."
      # Replace 'your-website-folder' with the name of the folder in your repo
      # If your files are at the root, use '.'
      - aws s3 sync . s3://csce412carolineholtman.me --delete --exclude ".git/*" --exclude "buildspec.yml"
artifacts:
  files:
    - '**/*'
